version: "3.7"

services:
  nxmeta:
    image: nxmeta
    container_name: nxmeta-test
    build: .
    restart: unless-stopped
    environment:
      - TZ=Americas/Los_Angeles
    volumes:
      - ./.mount/config:/config
      - ./.mount/media:/media
      - ./.mount/archive:/archive
    network_mode: bridge
    ports:
      - 7001:7001
